name: Checkstyle Validation

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'feature/**'
      - 'hotfix/*'

jobs:
  checkstyle:
    name: Check style
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run Checkstyle
      run: mvn checkstyle:check

    - name: Upload Checkstyle Report
      uses: actions/upload-artifact@v3
      with:
        name: checkstyle-report
        path: target/checkstyle-result.xml
