name: Release on Docker Hub when Merge to Main occurs

on:
  pull_request:
    branches:
      - main
    types:
      [closed]

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Determine Version from Branch Name
        id: version
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          echo "Branch name: $BRANCH_NAME"
          if [[ $BRANCH_NAME =~ ^release\/([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
          else
            echo "Branch does not follow the required 'release/major.minor.patch' format!"
            exit 1
          fi
          echo "Version to be released: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/2048"
          TAG=${{ env.version }}
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .

      - name: Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/2048"
          TAG=${{ env.version }}
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
