name: Assign Reviewers team to pull requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - develop

jobs:
  auto-assign-reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Assign Reviewers
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { ctxt } = require('@actions/github');

            const team = 'ReviewersGR12';

            const prNumber = ctxt.payload.pull_request.number;

            await github.rest.pulls.requestReviewers({
              owner: ctxt.repo.owner,
              repo: ctxt.repo.repo,
              pull_number: prNumber,
              team_reviewers: [team],
            });
